---
- hosts: jrwebdev
  become: true

  tasks:
  - name: create www dir
    file: path=/var/www state=directory

  - name: create jrwebdev dir
    file: path=/var/www/jrwebdev state=directory

  - name: deploy jrwebdev site
    synchronize:
      src: ~/t1cg/ltc-work/firstReactApp/dist
      dest: /var/www/jrwebdev

  - name: deploy jrwebdev gif
    copy:
      src: ~/t1cg/ltc-work/firstReactApp/package.json
      dest: /var/www/jrwebdev/package.json

  - name: get node
    raw: curl -sL https://rpm.nodesource.com/setup_6.x | sudo -E bash - && yum install nodejs -y  --enablerepo=nodesource

  - name: install dependencies
    raw: cd /var/www/jrwebdev/ && npm i

  - name: install NGINX
    raw: yum install nginx -y

  - name: set webserver dir
    raw: sed -i '44s/\/usr\/share\/nginx\/html/\/var\/www\/jrwebdev\/dist/' /etc/nginx/nginx.conf

  - name: starting NGINX
    service:
      name: nginx
      state: started
